/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_vertex {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_vertex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_vertex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_vertex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI(int value) {
    glpkJNI.glp_vertex_i_set(swigCPtr, value);
  }

  public int getI() {
    return glpkJNI.glp_vertex_i_get(swigCPtr);
  }

  public void setName(String value) {
    glpkJNI.glp_vertex_name_set(swigCPtr, value);
  }

  public String getName() {
    return glpkJNI.glp_vertex_name_get(swigCPtr);
  }

  public void setEntry(SWIGTYPE_p_void value) {
    glpkJNI.glp_vertex_entry_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getEntry() {
    long cPtr = glpkJNI.glp_vertex_entry_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setData(SWIGTYPE_p_void value) {
    glpkJNI.glp_vertex_data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = glpkJNI.glp_vertex_data_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setTemp(SWIGTYPE_p_void value) {
    glpkJNI.glp_vertex_temp_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getTemp() {
    long cPtr = glpkJNI.glp_vertex_temp_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setIn(SWIGTYPE_p_glp_arc value) {
    glpkJNI.glp_vertex_in_set(swigCPtr, SWIGTYPE_p_glp_arc.getCPtr(value));
  }

  public SWIGTYPE_p_glp_arc getIn() {
    long cPtr = glpkJNI.glp_vertex_in_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glp_arc(cPtr, false);
  }

  public void setOut(SWIGTYPE_p_glp_arc value) {
    glpkJNI.glp_vertex_out_set(swigCPtr, SWIGTYPE_p_glp_arc.getCPtr(value));
  }

  public SWIGTYPE_p_glp_arc getOut() {
    long cPtr = glpkJNI.glp_vertex_out_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glp_arc(cPtr, false);
  }

  public glp_vertex() {
    this(glpkJNI.new_glp_vertex(), true);
  }

}
