/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_arc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_arc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_arc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_arc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTail(SWIGTYPE_p_glp_vertex value) {
    glpkJNI.glp_arc_tail_set(swigCPtr, SWIGTYPE_p_glp_vertex.getCPtr(value));
  }

  public SWIGTYPE_p_glp_vertex getTail() {
    long cPtr = glpkJNI.glp_arc_tail_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glp_vertex(cPtr, false);
  }

  public void setHead(SWIGTYPE_p_glp_vertex value) {
    glpkJNI.glp_arc_head_set(swigCPtr, SWIGTYPE_p_glp_vertex.getCPtr(value));
  }

  public SWIGTYPE_p_glp_vertex getHead() {
    long cPtr = glpkJNI.glp_arc_head_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glp_vertex(cPtr, false);
  }

  public void setData(SWIGTYPE_p_void value) {
    glpkJNI.glp_arc_data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = glpkJNI.glp_arc_data_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setTemp(SWIGTYPE_p_void value) {
    glpkJNI.glp_arc_temp_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getTemp() {
    long cPtr = glpkJNI.glp_arc_temp_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setT_prev(SWIGTYPE_p_glp_arc value) {
    glpkJNI.glp_arc_t_prev_set(swigCPtr, SWIGTYPE_p_glp_arc.getCPtr(value));
  }

  public SWIGTYPE_p_glp_arc getT_prev() {
    long cPtr = glpkJNI.glp_arc_t_prev_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glp_arc(cPtr, false);
  }

  public void setT_next(SWIGTYPE_p_glp_arc value) {
    glpkJNI.glp_arc_t_next_set(swigCPtr, SWIGTYPE_p_glp_arc.getCPtr(value));
  }

  public SWIGTYPE_p_glp_arc getT_next() {
    long cPtr = glpkJNI.glp_arc_t_next_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glp_arc(cPtr, false);
  }

  public void setH_prev(SWIGTYPE_p_glp_arc value) {
    glpkJNI.glp_arc_h_prev_set(swigCPtr, SWIGTYPE_p_glp_arc.getCPtr(value));
  }

  public SWIGTYPE_p_glp_arc getH_prev() {
    long cPtr = glpkJNI.glp_arc_h_prev_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glp_arc(cPtr, false);
  }

  public void setH_next(SWIGTYPE_p_glp_arc value) {
    glpkJNI.glp_arc_h_next_set(swigCPtr, SWIGTYPE_p_glp_arc.getCPtr(value));
  }

  public SWIGTYPE_p_glp_arc getH_next() {
    long cPtr = glpkJNI.glp_arc_h_next_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glp_arc(cPtr, false);
  }

  public glp_arc() {
    this(glpkJNI.new_glp_arc(), true);
  }

}
