/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_smcp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_smcp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_smcp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_smcp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMsg_lev(int value) {
    glpkJNI.glp_smcp_msg_lev_set(swigCPtr, this, value);
  }

  public int getMsg_lev() {
    return glpkJNI.glp_smcp_msg_lev_get(swigCPtr, this);
  }

  public void setMeth(int value) {
    glpkJNI.glp_smcp_meth_set(swigCPtr, this, value);
  }

  public int getMeth() {
    return glpkJNI.glp_smcp_meth_get(swigCPtr, this);
  }

  public void setPricing(int value) {
    glpkJNI.glp_smcp_pricing_set(swigCPtr, this, value);
  }

  public int getPricing() {
    return glpkJNI.glp_smcp_pricing_get(swigCPtr, this);
  }

  public void setR_test(int value) {
    glpkJNI.glp_smcp_r_test_set(swigCPtr, this, value);
  }

  public int getR_test() {
    return glpkJNI.glp_smcp_r_test_get(swigCPtr, this);
  }

  public void setTol_bnd(double value) {
    glpkJNI.glp_smcp_tol_bnd_set(swigCPtr, this, value);
  }

  public double getTol_bnd() {
    return glpkJNI.glp_smcp_tol_bnd_get(swigCPtr, this);
  }

  public void setTol_dj(double value) {
    glpkJNI.glp_smcp_tol_dj_set(swigCPtr, this, value);
  }

  public double getTol_dj() {
    return glpkJNI.glp_smcp_tol_dj_get(swigCPtr, this);
  }

  public void setTol_piv(double value) {
    glpkJNI.glp_smcp_tol_piv_set(swigCPtr, this, value);
  }

  public double getTol_piv() {
    return glpkJNI.glp_smcp_tol_piv_get(swigCPtr, this);
  }

  public void setObj_ll(double value) {
    glpkJNI.glp_smcp_obj_ll_set(swigCPtr, this, value);
  }

  public double getObj_ll() {
    return glpkJNI.glp_smcp_obj_ll_get(swigCPtr, this);
  }

  public void setObj_ul(double value) {
    glpkJNI.glp_smcp_obj_ul_set(swigCPtr, this, value);
  }

  public double getObj_ul() {
    return glpkJNI.glp_smcp_obj_ul_get(swigCPtr, this);
  }

  public void setIt_lim(int value) {
    glpkJNI.glp_smcp_it_lim_set(swigCPtr, this, value);
  }

  public int getIt_lim() {
    return glpkJNI.glp_smcp_it_lim_get(swigCPtr, this);
  }

  public void setTm_lim(int value) {
    glpkJNI.glp_smcp_tm_lim_set(swigCPtr, this, value);
  }

  public int getTm_lim() {
    return glpkJNI.glp_smcp_tm_lim_get(swigCPtr, this);
  }

  public void setOut_frq(int value) {
    glpkJNI.glp_smcp_out_frq_set(swigCPtr, this, value);
  }

  public int getOut_frq() {
    return glpkJNI.glp_smcp_out_frq_get(swigCPtr, this);
  }

  public void setOut_dly(int value) {
    glpkJNI.glp_smcp_out_dly_set(swigCPtr, this, value);
  }

  public int getOut_dly() {
    return glpkJNI.glp_smcp_out_dly_get(swigCPtr, this);
  }

  public void setPresolve(int value) {
    glpkJNI.glp_smcp_presolve_set(swigCPtr, this, value);
  }

  public int getPresolve() {
    return glpkJNI.glp_smcp_presolve_get(swigCPtr, this);
  }

  public void setFoo_bar(SWIGTYPE_p_double value) {
    glpkJNI.glp_smcp_foo_bar_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getFoo_bar() {
    long cPtr = glpkJNI.glp_smcp_foo_bar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public glp_smcp() {
    this(glpkJNI.new_glp_smcp(), true);
  }

}
