/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_attr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_attr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_attr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_attr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLevel(int value) {
    glpkJNI.glp_attr_level_set(swigCPtr, this, value);
  }

  public int getLevel() {
    return glpkJNI.glp_attr_level_get(swigCPtr, this);
  }

  public void setOrigin(int value) {
    glpkJNI.glp_attr_origin_set(swigCPtr, this, value);
  }

  public int getOrigin() {
    return glpkJNI.glp_attr_origin_get(swigCPtr, this);
  }

  public void setKlass(int value) {
    glpkJNI.glp_attr_klass_set(swigCPtr, this, value);
  }

  public int getKlass() {
    return glpkJNI.glp_attr_klass_get(swigCPtr, this);
  }

  public void setFoo_bar(SWIGTYPE_p_double value) {
    glpkJNI.glp_attr_foo_bar_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getFoo_bar() {
    long cPtr = glpkJNI.glp_attr_foo_bar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public glp_attr() {
    this(glpkJNI.new_glp_attr(), true);
  }

}
