/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_iptcp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_iptcp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_iptcp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_iptcp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMsg_lev(int value) {
    glpkJNI.glp_iptcp_msg_lev_set(swigCPtr, this, value);
  }

  public int getMsg_lev() {
    return glpkJNI.glp_iptcp_msg_lev_get(swigCPtr, this);
  }

  public void setOrd_alg(int value) {
    glpkJNI.glp_iptcp_ord_alg_set(swigCPtr, this, value);
  }

  public int getOrd_alg() {
    return glpkJNI.glp_iptcp_ord_alg_get(swigCPtr, this);
  }

  public void setFoo_bar(SWIGTYPE_p_double value) {
    glpkJNI.glp_iptcp_foo_bar_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getFoo_bar() {
    long cPtr = glpkJNI.glp_iptcp_foo_bar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public glp_iptcp() {
    this(glpkJNI.new_glp_iptcp(), true);
  }

}
