/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_iocp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_iocp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_iocp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_iocp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMsg_lev(int value) {
    glpkJNI.glp_iocp_msg_lev_set(swigCPtr, this, value);
  }

  public int getMsg_lev() {
    return glpkJNI.glp_iocp_msg_lev_get(swigCPtr, this);
  }

  public void setBr_tech(int value) {
    glpkJNI.glp_iocp_br_tech_set(swigCPtr, this, value);
  }

  public int getBr_tech() {
    return glpkJNI.glp_iocp_br_tech_get(swigCPtr, this);
  }

  public void setBt_tech(int value) {
    glpkJNI.glp_iocp_bt_tech_set(swigCPtr, this, value);
  }

  public int getBt_tech() {
    return glpkJNI.glp_iocp_bt_tech_get(swigCPtr, this);
  }

  public void setTol_int(double value) {
    glpkJNI.glp_iocp_tol_int_set(swigCPtr, this, value);
  }

  public double getTol_int() {
    return glpkJNI.glp_iocp_tol_int_get(swigCPtr, this);
  }

  public void setTol_obj(double value) {
    glpkJNI.glp_iocp_tol_obj_set(swigCPtr, this, value);
  }

  public double getTol_obj() {
    return glpkJNI.glp_iocp_tol_obj_get(swigCPtr, this);
  }

  public void setTm_lim(int value) {
    glpkJNI.glp_iocp_tm_lim_set(swigCPtr, this, value);
  }

  public int getTm_lim() {
    return glpkJNI.glp_iocp_tm_lim_get(swigCPtr, this);
  }

  public void setOut_frq(int value) {
    glpkJNI.glp_iocp_out_frq_set(swigCPtr, this, value);
  }

  public int getOut_frq() {
    return glpkJNI.glp_iocp_out_frq_get(swigCPtr, this);
  }

  public void setOut_dly(int value) {
    glpkJNI.glp_iocp_out_dly_set(swigCPtr, this, value);
  }

  public int getOut_dly() {
    return glpkJNI.glp_iocp_out_dly_get(swigCPtr, this);
  }

  public void setCb_func(SWIGTYPE_p_f_p_struct_glp_tree_p_void__void value) {
    glpkJNI.glp_iocp_cb_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_glp_tree_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_glp_tree_p_void__void getCb_func() {
    long cPtr = glpkJNI.glp_iocp_cb_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_glp_tree_p_void__void(cPtr, false);
  }

  public void setCb_info(SWIGTYPE_p_void value) {
    glpkJNI.glp_iocp_cb_info_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getCb_info() {
    long cPtr = glpkJNI.glp_iocp_cb_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setCb_size(int value) {
    glpkJNI.glp_iocp_cb_size_set(swigCPtr, this, value);
  }

  public int getCb_size() {
    return glpkJNI.glp_iocp_cb_size_get(swigCPtr, this);
  }

  public void setPp_tech(int value) {
    glpkJNI.glp_iocp_pp_tech_set(swigCPtr, this, value);
  }

  public int getPp_tech() {
    return glpkJNI.glp_iocp_pp_tech_get(swigCPtr, this);
  }

  public void setMip_gap(double value) {
    glpkJNI.glp_iocp_mip_gap_set(swigCPtr, this, value);
  }

  public double getMip_gap() {
    return glpkJNI.glp_iocp_mip_gap_get(swigCPtr, this);
  }

  public void setMir_cuts(int value) {
    glpkJNI.glp_iocp_mir_cuts_set(swigCPtr, this, value);
  }

  public int getMir_cuts() {
    return glpkJNI.glp_iocp_mir_cuts_get(swigCPtr, this);
  }

  public void setGmi_cuts(int value) {
    glpkJNI.glp_iocp_gmi_cuts_set(swigCPtr, this, value);
  }

  public int getGmi_cuts() {
    return glpkJNI.glp_iocp_gmi_cuts_get(swigCPtr, this);
  }

  public void setCov_cuts(int value) {
    glpkJNI.glp_iocp_cov_cuts_set(swigCPtr, this, value);
  }

  public int getCov_cuts() {
    return glpkJNI.glp_iocp_cov_cuts_get(swigCPtr, this);
  }

  public void setClq_cuts(int value) {
    glpkJNI.glp_iocp_clq_cuts_set(swigCPtr, this, value);
  }

  public int getClq_cuts() {
    return glpkJNI.glp_iocp_clq_cuts_get(swigCPtr, this);
  }

  public void setPresolve(int value) {
    glpkJNI.glp_iocp_presolve_set(swigCPtr, this, value);
  }

  public int getPresolve() {
    return glpkJNI.glp_iocp_presolve_get(swigCPtr, this);
  }

  public void setBinarize(int value) {
    glpkJNI.glp_iocp_binarize_set(swigCPtr, this, value);
  }

  public int getBinarize() {
    return glpkJNI.glp_iocp_binarize_get(swigCPtr, this);
  }

  public void setFp_heur(int value) {
    glpkJNI.glp_iocp_fp_heur_set(swigCPtr, this, value);
  }

  public int getFp_heur() {
    return glpkJNI.glp_iocp_fp_heur_get(swigCPtr, this);
  }

  public void setPs_heur(int value) {
    glpkJNI.glp_iocp_ps_heur_set(swigCPtr, this, value);
  }

  public int getPs_heur() {
    return glpkJNI.glp_iocp_ps_heur_get(swigCPtr, this);
  }

  public void setPs_tm_lim(int value) {
    glpkJNI.glp_iocp_ps_tm_lim_set(swigCPtr, this, value);
  }

  public int getPs_tm_lim() {
    return glpkJNI.glp_iocp_ps_tm_lim_get(swigCPtr, this);
  }

  public void setUse_sol(int value) {
    glpkJNI.glp_iocp_use_sol_set(swigCPtr, this, value);
  }

  public int getUse_sol() {
    return glpkJNI.glp_iocp_use_sol_get(swigCPtr, this);
  }

  public void setSave_sol(String value) {
    glpkJNI.glp_iocp_save_sol_set(swigCPtr, this, value);
  }

  public String getSave_sol() {
    return glpkJNI.glp_iocp_save_sol_get(swigCPtr, this);
  }

  public void setAlien(int value) {
    glpkJNI.glp_iocp_alien_set(swigCPtr, this, value);
  }

  public int getAlien() {
    return glpkJNI.glp_iocp_alien_get(swigCPtr, this);
  }

  public void setFoo_bar(SWIGTYPE_p_double value) {
    glpkJNI.glp_iocp_foo_bar_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getFoo_bar() {
    long cPtr = glpkJNI.glp_iocp_foo_bar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public glp_iocp() {
    this(glpkJNI.new_glp_iocp(), true);
  }

}
