/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_bfcp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_bfcp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_bfcp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_bfcp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMsg_lev(int value) {
    glpkJNI.glp_bfcp_msg_lev_set(swigCPtr, this, value);
  }

  public int getMsg_lev() {
    return glpkJNI.glp_bfcp_msg_lev_get(swigCPtr, this);
  }

  public void setType(int value) {
    glpkJNI.glp_bfcp_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return glpkJNI.glp_bfcp_type_get(swigCPtr, this);
  }

  public void setLu_size(int value) {
    glpkJNI.glp_bfcp_lu_size_set(swigCPtr, this, value);
  }

  public int getLu_size() {
    return glpkJNI.glp_bfcp_lu_size_get(swigCPtr, this);
  }

  public void setPiv_tol(double value) {
    glpkJNI.glp_bfcp_piv_tol_set(swigCPtr, this, value);
  }

  public double getPiv_tol() {
    return glpkJNI.glp_bfcp_piv_tol_get(swigCPtr, this);
  }

  public void setPiv_lim(int value) {
    glpkJNI.glp_bfcp_piv_lim_set(swigCPtr, this, value);
  }

  public int getPiv_lim() {
    return glpkJNI.glp_bfcp_piv_lim_get(swigCPtr, this);
  }

  public void setSuhl(int value) {
    glpkJNI.glp_bfcp_suhl_set(swigCPtr, this, value);
  }

  public int getSuhl() {
    return glpkJNI.glp_bfcp_suhl_get(swigCPtr, this);
  }

  public void setEps_tol(double value) {
    glpkJNI.glp_bfcp_eps_tol_set(swigCPtr, this, value);
  }

  public double getEps_tol() {
    return glpkJNI.glp_bfcp_eps_tol_get(swigCPtr, this);
  }

  public void setMax_gro(double value) {
    glpkJNI.glp_bfcp_max_gro_set(swigCPtr, this, value);
  }

  public double getMax_gro() {
    return glpkJNI.glp_bfcp_max_gro_get(swigCPtr, this);
  }

  public void setNfs_max(int value) {
    glpkJNI.glp_bfcp_nfs_max_set(swigCPtr, this, value);
  }

  public int getNfs_max() {
    return glpkJNI.glp_bfcp_nfs_max_get(swigCPtr, this);
  }

  public void setUpd_tol(double value) {
    glpkJNI.glp_bfcp_upd_tol_set(swigCPtr, this, value);
  }

  public double getUpd_tol() {
    return glpkJNI.glp_bfcp_upd_tol_get(swigCPtr, this);
  }

  public void setNrs_max(int value) {
    glpkJNI.glp_bfcp_nrs_max_set(swigCPtr, this, value);
  }

  public int getNrs_max() {
    return glpkJNI.glp_bfcp_nrs_max_get(swigCPtr, this);
  }

  public void setRs_size(int value) {
    glpkJNI.glp_bfcp_rs_size_set(swigCPtr, this, value);
  }

  public int getRs_size() {
    return glpkJNI.glp_bfcp_rs_size_get(swigCPtr, this);
  }

  public void setFoo_bar(SWIGTYPE_p_double value) {
    glpkJNI.glp_bfcp_foo_bar_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getFoo_bar() {
    long cPtr = glpkJNI.glp_bfcp_foo_bar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public glp_bfcp() {
    this(glpkJNI.new_glp_bfcp(), true);
  }

}
