/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_mpscp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_mpscp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_mpscp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_mpscp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBlank(int value) {
    glpkJNI.glp_mpscp_blank_set(swigCPtr, this, value);
  }

  public int getBlank() {
    return glpkJNI.glp_mpscp_blank_get(swigCPtr, this);
  }

  public void setObj_name(String value) {
    glpkJNI.glp_mpscp_obj_name_set(swigCPtr, this, value);
  }

  public String getObj_name() {
    return glpkJNI.glp_mpscp_obj_name_get(swigCPtr, this);
  }

  public void setTol_mps(double value) {
    glpkJNI.glp_mpscp_tol_mps_set(swigCPtr, this, value);
  }

  public double getTol_mps() {
    return glpkJNI.glp_mpscp_tol_mps_get(swigCPtr, this);
  }

  public void setFoo_bar(SWIGTYPE_p_double value) {
    glpkJNI.glp_mpscp_foo_bar_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getFoo_bar() {
    long cPtr = glpkJNI.glp_mpscp_foo_bar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public glp_mpscp() {
    this(glpkJNI.new_glp_mpscp(), true);
  }

}
