/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class glp_cpxcp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected glp_cpxcp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_cpxcp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glpkJNI.delete_glp_cpxcp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFoo_bar(SWIGTYPE_p_double value) {
    glpkJNI.glp_cpxcp_foo_bar_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getFoo_bar() {
    long cPtr = glpkJNI.glp_cpxcp_foo_bar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public glp_cpxcp() {
    this(glpkJNI.new_glp_cpxcp(), true);
  }

}
