/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.littlepancake.glpk.jni;

public class SWIGTYPE_p_glp_tree {
  private long swigCPtr;

  protected SWIGTYPE_p_glp_tree(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_glp_tree() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_glp_tree obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

